=== m-31/qedeq/QedeqKernelSe/src/org/qedeq/kernel/xml/schema/parser.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="parser">
		<xs:annotation>
			<xs:documentation>Root element.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="prefixOperator">
						<xs:complexType>
							<xs:attribute name="startSymbol" type="xs:string" use="required"/>
							<xs:attribute name="qedeq" type="xs:string" use="required"/>
							<xs:attribute name="qedeqArgument" type="xs:string" use="optional"/>
							<xs:attribute name="priority" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="max" type="xs:nonNegativeInteger" use="optional"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="infixOperator">
						<xs:complexType>
							<xs:attribute name="startSymbol" type="xs:string" use="required"/>
							<xs:attribute name="qedeq" type="xs:string" use="required"/>
							<xs:attribute name="qedeqArgument" type="xs:string" use="optional"/>
							<xs:attribute name="priority" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="max" type="xs:nonNegativeInteger" use="optional"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="functionOperator">
						<xs:complexType>
							<xs:attribute name="startSymbol" type="xs:string" use="required"/>
							<xs:attribute name="qedeq" type="xs:string" use="required"/>
							<xs:attribute name="qedeqArgument" type="xs:string" use="optional"/>
							<xs:attribute name="priority" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="max" type="xs:nonNegativeInteger" use="optional"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="complexOperator">
						<xs:complexType>
							<xs:attribute name="startSymbol" type="xs:string" use="required"/>
							<xs:attribute name="separatorSymbol" type="xs:string" use="required"/>
							<xs:attribute name="endSymbol" type="xs:string" use="required"/>
							<xs:attribute name="qedeq" type="xs:string" use="required"/>
							<xs:attribute name="qedeqArgument" type="xs:string" use="optional"/>
							<xs:attribute name="priority" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
							<xs:attribute name="max" type="xs:nonNegativeInteger" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="operatorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="prefix"/>
			<xs:enumeration value="infix"/>
			<xs:enumeration value="function"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== m-31/qedeq/QedeqKernelBoTest/data/parser/asciiMathOperators.xml
<?xml version="1.0" encoding="UTF-8"?>
<parser 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.qedeq.org/0_04_07/xml/parser.xsd">
 	<prefixOperator 
 		startSymbol	="~"
 		qedeq		="NOT"
 		priority	="110"
 		min		="1"
 		max		="1"
 	/>
 	<infixOperator 
 		startSymbol	="&amp;"
 		qedeq		="AND"
 		priority	="100"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="v"
 		qedeq		="OR"
 		priority	="90"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="-&gt;"
 		qedeq		="IMPL"
 		priority	="80"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="&lt;-&gt;"
 		qedeq		="EQUI"
 		priority	="80"
 		min		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="A"
 		qedeq		="ALL"
 		priority	="140"
 		min		="2"
 		max		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="E"
 		qedeq		="EXISTS"
 		priority	="140"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="in"
 		qedeq		="IN"
 		priority	="200"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="="
 		qedeq		="EQUAL"
 		priority	="200"
 		min		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="set"
 		qedeq		="isSet"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol =","
 		endSymbol	="}"
 		qedeq		="SET"
 		priority	="10"
 		min		="0"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol ="|"
 		endSymbol	="}"
 		qedeq		="SETDEF"
 		priority	="10"
 		min		="2"
 		max		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="P"
 		qedeq		="PREDVAR_1"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<prefixOperator 
 		startSymbol	="Q"
 		qedeq		="PREDVAR_2"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<infixOperator 
 		startSymbol	="union"
 		qedeq		="UNION"
 		priority	="30"
 		min		="2"
 	/>
    <infixOperator 
        startSymbol ="inter"
        qedeq       ="INTER"
        priority    ="40"
        min         ="2"
 	/>
    <functionOperator 
        startSymbol ="function"
        qedeq       ="FUNC"
        priority    ="40"
        min         ="2"
        max         ="3"
    />

</parser>
<!--
        operators.add(new Operator("~",      "NOT",   110, 1, 1, 1));
        operators.add(new Operator("&",      "AND",   100, 0, 2));
        operators.add(new Operator("v",      "OR",     90, 0, 2));
        operators.add(new Operator("->",     "IMPL",   80, 0, 2, 2));
        operators.add(new Operator("<->",    "EQUI",   80, 0, 2));
        operators.add(new Operator("A",      "ALL",    140, 1, 2, 2));
        operators.add(new Operator("E",      "EXISTS", 140, 1, 2, 2));
        operators.add(new Operator("in",     "IN",    200, 0, 2, 2));
        operators.add(new Operator("=",      "EQUAL", 200, 0, 2));
        operators.add(new Operator("set",    "isSet", 200, 1, 1, 1));
        operators.add(new Operator("{", ",", "}", "SET", 10, 0));
        operators.add(new Operator("{", "|", "}", "SETDEF", 10, 2, 2));
        operators.add(new Operator("P",       "PREDVAR_1",  200, 1, 1, 1));
        operators.add(new Operator("Q",       "PREDVAR_2",  200, 1, 1, 1));
        operators.add(new Operator("union",   "UNION",       30, 0, 2));
        operators.add(new Operator("inter",   "INTER",       40, 0, 2));
-->

=== m-31/qedeq/QedeqGuiSe/src/config/textMathOperators.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<parser 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.qedeq.org/0_04_07/xml/parser.xsd">
    <prefixOperator 
        startSymbol ="~"
        qedeq       ="NOT"
        priority    ="110"
        min         ="1"
        max         ="1"
    />
    <infixOperator 
        startSymbol ="&amp;"
        qedeq       ="AND"
        priority    ="100"
        min         ="2"
    />
    <infixOperator 
        startSymbol ="v"
        qedeq       ="OR"
        priority    ="90"
        min         ="2"
    />
    <infixOperator 
        startSymbol ="-&gt;"
        qedeq       ="IMPL"
        priority    ="80"
        min         ="2"
        max         ="2"
    />
    <infixOperator 
        startSymbol ="&lt;-&gt;"
        qedeq       ="EQUI"
        priority    ="80"
        min         ="2"
    />
    <prefixOperator 
        startSymbol ="A"
        qedeq       ="FORALL"
        priority    ="140"
        min         ="2"
        max         ="2"
    />
    <prefixOperator 
        startSymbol ="E!"
        qedeq       ="EXISTSU"
        priority    ="150"
        min         ="2"
        max         ="2"
    />
    <prefixOperator 
        startSymbol ="E"
        qedeq       ="EXISTS"
        priority    ="140"
        min         ="2"
        max         ="2"
    />
    <infixOperator 
        startSymbol ="in"
        qedeq       ="PREDCON"
        qedeqArgument   = "in"
        priority    ="200"
        min         ="2"
        max         ="2"
    />
    <infixOperator 
        startSymbol ="~in"
        qedeq       ="PREDCON"
        qedeqArgument   = "notIn"
        priority    ="200"
        min         ="2"
        max         ="2"
    />
    <infixOperator 
        startSymbol ="="
        qedeq       ="PREDCON"
        qedeqArgument   ="equal"
        priority    ="150"
        min         ="2"
    />
    <functionOperator 
        startSymbol ="set"
        qedeq       ="PREDCON"
        qedeqArgument   ="isSet"
        priority    ="200"
        min         ="1"
        max         ="1"
    />
    <complexOperator 
        startSymbol ="{"
        separatorSymbol =","
        endSymbol   ="}"
        qedeq       ="CLASSLIST"
        priority    ="10"
        min         ="0"
    />
    <complexOperator 
        startSymbol = "{"
        separatorSymbol = "|"
        endSymbol   = "}"
        qedeq       = "CLASS"
        priority    = "10"
        min         = "2"
        max         = "2"
    />
    <functionOperator 
        startSymbol = "C"
        qedeq       = "FUNCON"
        qedeqArgument   = "complement"
        priority    = "400"
        min         = "1"
        max         = "1"
    />
    
    <functionOperator 
        startSymbol = "a"
        qedeq       = "PREDVAR"
        qedeqArgument = "\alpha"
        priority    = "200"
        min         = "0"
        max         = "2"
    />
    <functionOperator 
        startSymbol = "b"
        qedeq       = "PREDVAR"
        qedeqArgument = "\beta"
        priority    = "200"
        min         = "0"
        max         = "2"
    />
    <functionOperator 
        startSymbol = "c"
        qedeq       = "PREDVAR"
        qedeqArgument   = "\gamma"
        priority    = "200"
        min         ="0"
    />
    <functionOperator 
        startSymbol = "d"
        qedeq       = "PREDVAR"
        qedeqArgument   = "\delta"
        priority     = "200"
        min          = "0"
        max          = "2"
    />
    <functionOperator 
        startSymbol  = "f"
        qedeq        = "FUNVAR"
        qedeqArgument = "f"
        priority    = "200"
        min         = "1"
    />
    <functionOperator 
        startSymbol = "g"
        qedeq         = "FUNVAR"
        qedeqArgument = "g"
        priority     = "200"
        min             = "0"
    />
    <functionOperator 
        startSymbol = "h"
        qedeq       = "FUNVAR"
        qedeqArgument   = "A"
        priority    = "200"
        min         = "1"
    />
    <functionOperator 
        startSymbol     = "T"
        qedeq         = "PREDCON"
        qedeqArgument = "TRUE"
        priority     = "200"
        min             = "0"
        max             = "0"
    />
    <functionOperator 
        startSymbol     = "F"
        qedeq         = "PREDCON"
        qedeqArgument = "FALSE"
        priority     = "200"
        min             = "0"
        max             = "0"
    />
    <functionOperator 
        startSymbol     = "x1"
        qedeq         = "VAR"
        qedeqArgument = "x_1"
        priority     = "200"
        min             = "0"
        max           = "0"
    />
    <functionOperator 
        startSymbol   = "w"
        qedeq         = "VAR"
        qedeqArgument = "x"
        priority      = "200"
        min           = "0"
        max           = "0"
    />
    <functionOperator 
        startSymbol     = "x"
        qedeq         = "VAR"
        qedeqArgument = "x"
        priority     = "200"
        min             = "0"
        max           = "0"
    />
    <functionOperator 
        startSymbol     = "y"
        qedeq         = "VAR"
        qedeqArgument = "y"
        priority     = "200"
        min             = "0"
        max           = "0"
    />
    <functionOperator 
        startSymbol     = "z"
        qedeq         = "VAR"
        qedeqArgument = "z"
        priority     = "200"
        min             = "0"
        max           = "0"
    />
    <functionOperator 
        startSymbol     = "dmn"
        qedeq         = "PREDCON"
        qedeqArgument = "dmn"
        priority     = "200"
        min             = "1"
        max           = "1"
    />
    <functionOperator 
        startSymbol     = "rng"
        qedeq         = "PREDCON"
        qedeqArgument = "rng"
        priority     = "200"
        min             = "1"
        max           = "1"
    />
    <infixOperator 
        startSymbol     = "u"
        qedeq         = "FUNCON"
        qedeqArgument = "union"
        priority     = "330"
        min             = "2"
    />
    <infixOperator 
        startSymbol     = "n"
        qedeq         = "FUNCON"
        qedeqArgument = "intersection"
        priority     = "340"
        min             = "2"
    />
    <infixOperator 
        startSymbol     = "&lt;="
        qedeq         = "PREDCON"
        qedeqArgument = "subset"
        priority     = "200"
        min             = "2"
    />
    <functionOperator 
        startSymbol     = "P"
        qedeq         = "FUNCON"
        qedeqArgument     = "power"
        priority     = "200"
        min         = "1"
        max               = "1"
    />
    
    
   <functionOperator 
       startSymbol     = "Ru"
       qedeq         = "FUNCON"
       qedeqArgument = "russell"
       priority     = "200"
       min             = "0"
       max           = "0"
   />
    <functionOperator 
        startSymbol     = "0"
        qedeq         = "FUNCON"
        qedeqArgument = "emptySet"
        priority     = "200"
        min             = "0"
        max           = "0"
    />

    <functionOperator 
        startSymbol     = "V"
        qedeq         = "FUNCON"
        qedeqArgument = "universalClass"
        priority     = "200"
        min             = "0"
        max           = "0"
    />
    
    
</parser>

=== m-31/qedeq/QedeqKernelBoTest/data/parser/latexMathOperators.xml
<?xml version="1.0" encoding="UTF-8"?>
<parser 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.qedeq.org/0_04_07/xml/parser.xsd">
 	<prefixOperator 
 		startSymbol	="neg"
 		qedeq		="NOT"
 		priority	="110"
 		min		="1"
 		max		="1"
 	/>
 	<infixOperator 
 		startSymbol	="land"
 		qedeq		="AND"
 		priority	="100"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="lor"
 		qedeq		="OR"
 		priority	="90"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="impl"
 		qedeq		="IMPL"
 		priority	="80"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="equi"
 		qedeq		="EQUI"
 		priority	="80"
 		min		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="forall"
 		qedeq		="ALL"
 		priority	="140"
 		min		="2"
 		max		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="exists"
 		qedeq		="EXISTS"
 		priority	="140"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="in"
 		qedeq		="IN"
 		priority	="200"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="="
 		qedeq		="EQUAL"
 		priority	="200"
 		min		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="isSet"
 		qedeq		="isSet"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<prefixOperator 
 		startSymbol	="isSet"
 		qedeq		="isSet"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol =","
 		endSymbol	="}"
 		qedeq		="SET"
 		priority	="10"
 		min		="0"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol ="|"
 		endSymbol	="}"
 		qedeq		="SET"
 		priority	="10"
 		min		="2"
 		max		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="phi"
 		qedeq		="PREDVAR_1"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<prefixOperator 
 		startSymbol	="psi"
 		qedeq		="PREDVAR_2"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<functionOperator 
 		startSymbol	="alpha"
 		qedeq		="PREDVAR_3"
 		priority	="200"
 		min		="0"
 	/>
 	<functionOperator 
 		startSymbol	="beta"
 		qedeq		="PREDVAR_4"
 		priority	="200"
 		min		="0"
 	/>
 	<infixOperator 
 		startSymbol	="cup"
 		qedeq		="UNION"
 		priority	="30"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="cap"
 		qedeq		="INTER"
 		priority	="40"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="defp"
 		qedeq		="DEFP"
 		priority	="10"
 		min		="2"
 		max		="2"
 	/>
 	<functionOperator 
 		startSymbol	="A"
 		qedeq		="A"
 		priority	="200"
 		min		="0"
 		max		="0"
 	/>
 	<functionOperator 
 		startSymbol	="B"
 		qedeq		="B"
 		priority	="200"
 		min		="0"
 		max		="0"
 	/>
 	<functionOperator 
 		startSymbol	="C"
 		qedeq		="C"
 		priority	="200"
 		min		="0"
 		max		="0"
 	/>
 	<functionOperator 
 		startSymbol	="x"
 		qedeq		="x"
 		priority	="200"
 		min		="0"
 		max		="0"
 	/>
 	<functionOperator 
 		startSymbol	="x_1"
 		qedeq		="x_1"
 		priority	="200"
 		min		="0"
 		max		="0"
 	/>
 	<functionOperator 
 		startSymbol	="y"
 		qedeq		="y"
 		priority	="200"
 		min		="0"
 		max		="0"
 	/>
</parser>
<!--


        operators.add(new Operator("neg",     "NOT",   110, 1, 1, 1));
        operators.add(new Operator("land",    "AND",   100, 0, 2));
        operators.add(new Operator("lor",     "OR",     90, 0, 2));
        operators.add(new Operator("impl",    "IMPL",   80, 0, 2, 2));
        operators.add(new Operator("equi",    "EQUI",   80, 0, 2));
        operators.add(new Operator("forall",  "ALL",    140, 1, 2, 2));
        operators.add(new Operator("exists",  "EXISTS", 140, 1, 2, 2));
        operators.add(new Operator("in",      "IN",    200, 0, 2, 2));
        operators.add(new Operator("=",         "EQUAL", 200, 0, 2));
        operators.add(new Operator("isSet",     "isSet", 200, 1, 1, 1));
        operators.add(new Operator("{", ",", "}", "SET", 10, 0));
        operators.add(new Operator("{", "|", "}", "SETDEF", 10, 2, 2));
        operators.add(new Operator("phi",     "PREDVAR_1",  200, 1, 1, 1));
        operators.add(new Operator("psi",     "PREDVAR_2",  200, 1, 1, 1));
        operators.add(new Operator("alpha",   "PREDVAR_3",  200, 4, 0, -1));
        operators.add(new Operator("beta",    "PREDVAR_4",  200, 4, 0, -1));
        operators.add(new Operator("cup",     "UNION",    30, 0, 2));
        operators.add(new Operator("cap",     "INTER",    40, 0, 2));
        operators.add(new Operator("defp",    "DEFP", 10, 0, 2));
-->

=== m-31/qedeq/QedeqKernelBoTest/data/parser/simpleMathOperators.xml
<?xml version="1.0" encoding="UTF-8"?>
<parser 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.qedeq.org/0_04_07/xml/parser.xsd">
 	<prefixOperator 
 		startSymbol	="~"
 		qedeq		="NOT"
 		priority	="110"
 		min		="1"
 		max		="1"
 	/>
 	<prefixOperator 
 		startSymbol	="-"
 		qedeq		="NOT"
 		priority	="110"
 		min		="1"
 		max		="1"
 	/>
 	<infixOperator 
 		startSymbol	="&amp;"
 		qedeq		="AND"
 		priority	="100"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="|"
 		qedeq		="OR"
 		priority	="90"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="-&gt;"
 		qedeq		="IMPL"
 		priority	="80"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="=&gt;"
 		qedeq		="IMPL"
 		priority	="80"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="&lt;-&gt;"
 		qedeq		="EQUI"
 		priority	="80"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="&lt;=&gt;"
 		qedeq		="EQUI"
 		priority	="80"
 		min		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="all"
 		qedeq		="ALL"
 		priority	="40"
 		min		="2"
 		max		="3"
 	/>
 	<prefixOperator 
 		startSymbol	="exists"
 		qedeq		="EXISTS"
 		priority	="40"
 		min		="2"
 		max		="3"
 	/>
 	<infixOperator 
 		startSymbol	="in"
 		qedeq		="IN"
 		priority	="200"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="="
 		qedeq		="EQUAL"
 		priority	="200"
 		min		="2"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol =","
 		endSymbol	="}"
 		qedeq		="SET"
 		priority	="200"
 		min		="0"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol =":"
 		endSymbol	="}"
 		qedeq		="SETPROP"
 		priority	="200"
 		min		="2"
 		max		="2"
 	/>
</parser>
<!--


        operators.add(new Operator("~",      "NOT",   110, 1, 1, 1));
        operators.add(new Operator("-",      "NOT",   110, 1, 1, 1));
        operators.add(new Operator("&amp;",      "AND",   100, 0, 2));
        operators.add(new Operator("|",      "OR",     90, 0, 2));
//        operators.put("v",      new Operator("v",      "OR",     90, 0, 2));
        operators.add(new Operator("-&gt;",     "IMPL",   80, 0, 2, 2));
        operators.add(new Operator("=&gt;",     "IMPL",   80, 0, 2, 2));
        operators.add(new Operator("&lt;-&gt;",    "EQUI",   80, 0, 2));
        operators.add(new Operator("&lt;=&gt;",    "EQUI",   80, 0, 2));
        operators.add(new Operator("all",    "ALL",    40, 1, 2, 3));
        operators.add(new Operator("exists", "EXISTS", 40, 1, 2, 3));
        operators.add(new Operator("in",     "IN",    200, 0, 2, 2));
        operators.add(new Operator("=",      "EQUAL", 200, 0, 2));
        operators.add(new Operator("{", ",", "}", "SET", 200, 0));
        operators.add(new Operator("{", ":", "}", "SETPROP", 200, 2, 2));
-->

=== m-31/qedeq/QedeqGuiSe/src/config/latexMathOperators.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<parser 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.qedeq.org/0_04_07/xml/parser.xsd">
 	<prefixOperator 
 		startSymbol	="neg"
 		qedeq		="NOT"
 		priority	="110"
 		min		="1"
 		max		="1"
 	/>
 	<infixOperator 
 		startSymbol	="land"
 		qedeq		="AND"
 		priority	="100"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="lor"
 		qedeq		="OR"
 		priority	="90"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="impl"
 		qedeq		="IMPL"
 		priority	="80"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="rightarrow"
 		qedeq		="IMPL"
 		priority	="80"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="equi"
 		qedeq		="EQUI"
 		priority	="80"
 		min		="2"
 	/>
 	<infixOperator 
 		startSymbol	="leftrightarrow"
 		qedeq		="EQUI"
 		priority	="80"
 		min		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="forall"
 		qedeq		="FORALL"
 		priority	="140"
 		min		="2"
 		max		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="exists!"
 		qedeq		="EXISTSU"
 		priority	="150"
 		min		="2"
 		max		="2"
 	/>
 	<prefixOperator 
 		startSymbol	="exists"
 		qedeq		="EXISTS"
 		priority	="140"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="in"
 		qedeq		="PREDCON"
 		qedeqArgument   = "in"
 		priority	="200"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="notin"
 		qedeq		="PREDCON"
 		qedeqArgument   = "notIn"
 		priority	="200"
 		min		="2"
 		max		="2"
 	/>
 	<infixOperator 
 		startSymbol	="="
 		qedeq		="PREDCON"
 		qedeqArgument   ="equal"
 		priority	="150"
 		min		="2"
 	/>
 	<functionOperator 
 		startSymbol	="isSet"
 		qedeq		="PREDCON"
 		qedeqArgument   ="isSet"
 		priority	="200"
 		min		="1"
 		max		="1"
 	/>
 	<complexOperator 
 		startSymbol	="{"
 		separatorSymbol =","
 		endSymbol	="}"
 		qedeq		="CLASSLIST"
 		priority	="10"
 		min		="0"
 	/>
 	<complexOperator 
 		startSymbol	    = "{"
 		separatorSymbol = "|"
 		endSymbol	    = "}"
 		qedeq		    = "CLASS"
 		priority	    = "10"
 		min		        = "2"
 		max		        = "2"
 	/>
 	<functionOperator 
 		startSymbol	    = "overline"
 		qedeq		  = "FUNCON"
 		qedeqArgument = "complement"
 		priority	    = "400"
 		min		        = "1"
 		max		        = "1"
 	/>
 	
 	<functionOperator 
 		startSymbol	  = "phi"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "\phi"
 		priority	  = "200"
 		min		      = "1"
 		max		      = "2"
 	/>
 	<functionOperator 
 		startSymbol	  = "psi"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "\psi"
 		priority	  = "200"
 		min		      = "1"
 		max		      = "2"
 	/>
 	<functionOperator 
 		startSymbol	  = "alpha"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "\alpha"
 		priority	  = "200"
 		min		="0"
 	/>
 	<functionOperator 
 		startSymbol	  = "beta"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "\beta"
 		priority	  = "200"
 		min		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "P"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "P"
 		priority	  = "200"
 		min		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "Q"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "Q"
 		priority	  = "200"
 		min		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "A"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "A"
 		priority	  = "200"
 		min		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "B"
 		qedeq		  = "PREDVAR"
 		qedeqArgument = "B"
 		priority	  = "200"
 		min		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "C"
 		qedeq		  = "PREDVAR"
 		qedeqArgument 	= "C"
 		priority	  = "200"
 		min		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "top"
 		qedeq		  = "PREDCON"
 		qedeqArgument = "TRUE"
 		priority	  = "200"
 		min		      = "0"
 		max		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "bot"
 		qedeq		  = "PREDCON"
 		qedeqArgument = "FALSE"
 		priority	  = "200"
 		min		      = "0"
 		max		      = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "x_1"
 		qedeq		  = "VAR"
 		qedeqArgument = "x_1"
 		priority	  = "200"
 		min		      = "0"
 		max           = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "x"
 		qedeq		  = "VAR"
 		qedeqArgument = "x"
 		priority	  = "200"
 		min		      = "0"
 		max           = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "y"
 		qedeq		  = "VAR"
 		qedeqArgument = "y"
 		priority	  = "200"
 		min		      = "0"
 		max           = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "z"
 		qedeq		  = "VAR"
 		qedeqArgument = "z"
 		priority	  = "200"
 		min		      = "0"
 		max           = "0"
 	/>
 	<functionOperator 
 		startSymbol	  = "dmn"
 		qedeq		  = "PREDCON"
 		qedeqArgument = "dmn"
 		priority	  = "200"
 		min		      = "1"
 		max           = "1"
 	/>
 	<functionOperator 
 		startSymbol	  = "rng"
 		qedeq		  = "PREDCON"
 		qedeqArgument = "rng"
 		priority	  = "200"
 		min		      = "1"
 		max           = "1"
 	/>
 	<infixOperator 
 		startSymbol	  = "cup"
 		qedeq		  = "FUNCON"
 		qedeqArgument = "union"
 		priority	  = "330"
 		min		      = "2"
 	/>
 	<infixOperator 
 		startSymbol	  = "cap"
 		qedeq		  = "FUNCON"
 		qedeqArgument = "intersection"
 		priority	  = "340"
 		min		      = "2"
 	/>
 	<infixOperator 
 		startSymbol	  = "defp"
 		qedeq		  = "DEFP"
 		priority	  = "10"
 		min		      = "2"
 		max		      = "2"
 	/>
 	<infixOperator 
 		startSymbol	  = "deft"
 		qedeq		  = "DEFT"
 		priority	  = "10"
 		min		      = "2"
 		max		      = "2"
 	/>
 	<infixOperator 
 		startSymbol	  = ":="
 		qedeq		  = "DEFT"
 		priority	  = "10"
 		min		      = "2"
 		max		      = "2"
 	/>
 	<infixOperator 
 		startSymbol	  = "subset"
 		qedeq		  = "PREDCON"
 		qedeqArgument = "subset"
 		priority	  = "200"
 		min		      = "2"
 	/>
 	<functionOperator 
 		startSymbol	  = "power"
 		qedeq		  = "FUNCON"
 		qedeqArgument     = "power"
 		priority	  = "200"
 		min		  = "1"
 		max               = "1"
 	/>
 	
 	
	<functionOperator 
		startSymbol	  = "russell"
		qedeq		  = "FUNCON"
		qedeqArgument = "russell"
		priority	  = "200"
		min		      = "0"
		max           = "0"
	/>
 	<functionOperator 
 		startSymbol	  = "emptyset"
 		qedeq		  = "FUNCON"
 		qedeqArgument = "emptySet"
 		priority	  = "200"
 		min		      = "0"
 		max           = "0"
 	/>

 	<functionOperator 
 		startSymbol	  = "allClass"
 		qedeq		  = "FUNCON"
 		qedeqArgument = "universalClass"
 		priority	  = "200"
 		min		      = "0"
 		max           = "0"
 	/>
 	
 	
</parser>
